name: Fetch Updates

on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu latest
    steps:
      # - name: Checkout
      - uses: actions/checkout@v2
      # - name Setup Node
      - uses: actions/setup-node@v1
      - run: yarn
      - run: node hockey_data.js
      