name: Write Secrets

on:
  push:
    branches:
      - main
jobs:
  write-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DAMN SON"
      - name: Write a variable
        run: |
          ls ${{ github.workspace }}